services:
  mavric-ros-jazzy:
    container_name: mavric-ros-jazzy
    image: mavric-jazzy-dev
    build:
      context: .devcontainer/ROS Jazzy Dev Config
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace/ros2_ws_Jazzy
    command: >
      bash -lc "colcon build --symlink-install &&
      source install/setup.bash &&
      ros2 launch mavric_launch teleop.launch.py"
