# Drive Motors
FLD_ID = 1
FRD_ID = 6
BLD_ID = 5
BRD_ID = 3

# Steer Motors 
FLS_ID = 7
FRS_ID = 10
BLS_ID = 9
BRS_ID = 8

# Arm Motors
SHOULDER_PITCH_ID = 11
SHOULDER_ROT_ID = 12
ELBOW_PITCH_ID = 13
WRIST_PITCH_ID = 14
WRIST_ROT_ID = 15

# Claw PWM Channel
CLAW_CHANNEL = 1


# Drive Speed
MAX_DRIVE_SPEED = 0.2
NORMAL_DRIVE_SPEED = 0.1
MIN_DRIVE_SPEED = 0.05

# STEER ROTATION
DEFAULT_STEER_POS = 0.84
STEER_ROTATION_POS = 7
STEER_ROTATION_SPEED = 0.05
STEER_RIGHT_POS = 5
STEER_LEFT_POS = -5

# ARM SPEEDS
SHOULDER_PITCH_SPEED = 0.4
SHOULDER_ROT_SPEED = 0.2
ELBOW_PITCH_SPEED = 0.5
WRIST_PITCH_SPEED = 0.5
WRIST_ROT_SPEED = 0.5
CLAW_SPEED = 1

POS_MARGIN_ERROR = 0.8